"""Pushing and pulling probe artifacts through the Hugging Face Hub.

The transport half of step 6e-5. :mod:`visbench.hub.artifact` already writes a
self-contained file and refuses to load it against the wrong backbone; this
module only moves that file, and deliberately adds no rules of its own — a
downloaded probe goes through exactly the same :func:`load_probe` a local one
does, identity checks included.

**Downloading is the dangerous direction, and the guard is already in place.**
``load_probe`` reads with ``weights_only=True``, so a probe fetched from a
stranger's repository cannot execute code on the way in. That was built in 6e-4,
one step before a download button existed, precisely so it could not be
forgotten in the step where it starts to matter. Nothing here may add a load
path that bypasses it.

Needs ``huggingface_hub``: ``pip install visbench[hub]``. Imported inside the
functions that use it, so a core install can still save and load probes locally
and ``import visbench.hub`` does not require the extra.
"""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any

from visbench.hub.artifact import load_probe, probe_metadata, save_probe

__all__ = ["CARD_TEMPLATE", "load_probe_from_hub", "probe_card", "push_probe"]

#: Default filename inside a Hub repository.
#:
#: Fixed rather than derived from the task, so ``load_probe_from_hub`` can find
#: it without a listing call and a repository holding one probe has one obvious
#: file. A repository holding several passes ``filename=`` explicitly.
PROBE_FILENAME = "probe.pt"

CARD_TEMPLATE = """---
library_name: visbench
tags:
- visbench
- probing
- {task}
---

# {task} probe for `{backbone}`

A **trained probe head**, not a backbone. It is the small module VisBench fits
on top of frozen `{backbone}` features to measure what those features carry.

```python
import visbench
from visbench.hub import load_probe_from_hub

backbone = visbench.get_backbone("{backbone}")
probe = load_probe_from_hub("{repo_id}", backbone=backbone)
```

## It only works with this backbone

These weights were fitted on features from `{backbone}`, taken with
`pooling={pooling}` and `feature_mode={feature_mode}`. Loading them against
anything else is refused, because the failure is otherwise silent: a head fitted
on one pooling and fed another has the right shapes and produces a plausible,
wrong number.

| | |
| --- | --- |
| backbone | `{backbone}` |
| backbone key | `{backbone_key}` |
| task | `{task}` ({level}) |
| pooling | `{pooling}` (requested `{pooling_requested}`) |
| feature mode | `{feature_mode}` |
| layers | `{layers}` |
{metrics_rows}
## Reproducing it

{task_params}

Generated by [VisBench](https://github.com/turhancan97/VisBench).
"""


def probe_card(
    task: Any,
    backbone: Any,
    repo_id: str,
    metrics: dict[str, float] | None = None,
) -> str:
    """The README that goes in the repository beside the weights.

    A bare ``.pt`` on a model page tells a visitor nothing — least of all the
    one thing they must know, which is that these weights belong to exactly one
    backbone. The card is generated from the same metadata the artifact carries,
    so the page and the file cannot disagree.
    """
    meta = probe_metadata(task, backbone)
    rows = ""
    if metrics:
        rows = "\n**Reported scores**\n\n| metric | value |\n| --- | --- |\n" + "".join(
            f"| `{name}` | {value:.4f} |\n" for name, value in sorted(metrics.items())
        )

    params = meta["task_params"]
    if params:
        listed = "\n".join(f"- `{key}`: `{value}`" for key, value in sorted(params.items()))
        params_text = f"Fitted with:\n\n{listed}"
    else:
        params_text = "This probe records no training hyperparameters."

    return CARD_TEMPLATE.format(
        repo_id=repo_id,
        backbone=meta["backbone"],
        backbone_key=meta["backbone_key"],
        task=meta["task"],
        level=meta["level"],
        pooling=meta["pooling"],
        pooling_requested=meta["pooling_requested"],
        feature_mode=meta["feature_mode"],
        layers=meta["layers"],
        metrics_rows=rows,
        task_params=params_text,
    )


def _api(token: str | None = None) -> Any:
    """The Hub client, imported late so a core install still works."""
    try:
        from huggingface_hub import HfApi
    except ImportError as exc:  # pragma: no cover - needs the extra uninstalled
        raise ImportError(
            "Pushing and pulling probes needs huggingface_hub. Install it with "
            "`pip install visbench[hub]`. Saving and loading a probe to a local "
            "file works without it — see visbench.hub.save_probe."
        ) from exc
    return HfApi(token=token)


def push_probe(
    task: Any,
    repo_id: str,
    *,
    backbone: Any,
    metrics: dict[str, float] | None = None,
    private: bool = True,
    token: str | None = None,
    filename: str = PROBE_FILENAME,
    commit_message: str | None = None,
) -> str:
    """Upload a fitted probe and a generated card. Returns the repository URL.

    Parameters
    ----------
    private:
        **Defaults to private.** A push is not reversible in the way a local
        write is: once a repository is public it may have been fetched, and
        deleting it afterwards does not unpublish what was taken. Making it
        public is a decision the owner should make deliberately, not a default
        they discover afterwards.
    metrics:
        What this probe scored, for the card. Optional, and *not* verified —
        the card says these were reported, not that they were reproduced.

    Raises
    ------
    ValueError
        If the probe is unfitted or zero-shot, via :func:`save_probe`. That
        check runs **before** anything is uploaded, so a broken artifact never
        reaches a public URL.
    """
    api = _api(token)

    with tempfile.TemporaryDirectory() as tmp:
        staged = Path(tmp)
        # save_probe first: it refuses an unfitted or zero-shot probe, and doing
        # that before create_repo means a rejected push leaves nothing behind.
        save_probe(task, staged / filename, backbone=backbone)
        (staged / "README.md").write_text(probe_card(task, backbone, repo_id, metrics))

        api.create_repo(repo_id=repo_id, private=private, exist_ok=True)
        api.upload_folder(
            repo_id=repo_id,
            folder_path=str(staged),
            commit_message=commit_message or f"Add {task.name} probe for {backbone.name}",
        )

    return f"https://huggingface.co/{repo_id}"


def load_probe_from_hub(
    repo_id: str,
    *,
    backbone: Any,
    task: Any | None = None,
    strict: bool = True,
    filename: str = PROBE_FILENAME,
    revision: str | None = None,
    token: str | None = None,
    cache_dir: str | None = None,
) -> Any:
    """Download a probe and load it, with the same checks a local file gets.

    This is :func:`load_probe` with a download in front of it, and that is the
    whole design. A separate loading path for remote files is how one of them
    ends up without ``weights_only=True``, or without the backbone identity
    check — and a downloaded probe is exactly the one that most needs both.

    ``revision`` pins a commit. Worth passing for anything whose number you
    intend to quote: a Hub repository is mutable, so ``main`` today and ``main``
    next month are not promised to be the same weights.
    """
    try:
        from huggingface_hub import hf_hub_download
    except ImportError as exc:  # pragma: no cover - needs the extra uninstalled
        raise ImportError(
            "Pulling probes needs huggingface_hub. Install it with `pip install visbench[hub]`."
        ) from exc

    path = hf_hub_download(
        repo_id=repo_id,
        filename=filename,
        revision=revision,
        token=token,
        cache_dir=cache_dir,
    )
    return load_probe(path, backbone=backbone, task=task, strict=strict)
