"""Target tensors to RGB arrays. Pure functions, no I/O, no file formats.

Two rules govern everything here, and both exist because a picture is believed
more readily than a number.

**An invalid pixel is drawn as invalid.** :data:`INVALID_RGB` is magenta, which
appears in no colouriser's own output — greyscale has no hue, the normal-map
convention cannot reach full magenta for a unit vector, and VOC's palette does
not contain it. So a hole reads as a hole at a glance instead of as a plausible
dark pixel, which is the failure that makes a misread validity convention
survive inspection.

**A target and a prediction share one display range.** Scaling each panel to its
own extremes is the obvious implementation and it hides the most common way a
regression head is wrong: a prediction uniformly half the target's magnitude
renders *identically* to a correct one. :func:`display_range` is computed once,
from the target, over valid pixels only, and applied to both.

Greyscale rather than a perceptual colour map is a deliberate second-order
choice. It needs no lookup table and therefore no new dependency, and it cannot
manufacture structure: a viridis ramp puts visible boundaries at its own colour
transitions, and on a noisy magnitude map those read as edges in the data.
"""

from dataclasses import dataclass

import numpy as np
import torch

from visbench.viz.styles import COMPOSITE_KINDS, TargetStyle

__all__ = [
    "INVALID_RGB",
    "DisplayRange",
    "display_range",
    "target_to_rgb",
    "voc_palette",
]

#: Colour for a pixel with no ground truth. Chosen because no colouriser here
#: can produce it, so it is never ambiguous with real data.
INVALID_RGB: tuple[int, int, int] = (255, 0, 255)

#: Percentiles the display range spans. Not the full min/max: a single outlying
#: pixel — a specular highlight in a corner response, one far-wall depth reading
#: — otherwise compresses the whole frame into the bottom of the ramp and the
#: panel goes flat black while the data is fine.
_DISPLAY_PERCENTILES: tuple[float, float] = (2.0, 98.0)


@dataclass(frozen=True)
class DisplayRange:
    """The low and high values mapped to black and white.

    Carried explicitly, and reported in the caption, because it is the one
    piece of scaling a viewer cannot avoid applying. Stating it is what keeps
    the panel a measurement rather than an impression.
    """

    low: float
    high: float

    def normalise(self, values: np.ndarray) -> np.ndarray:
        """``values`` mapped to ``[0, 1]``, clipped at both ends."""
        span = self.high - self.low
        if not np.isfinite(span) or span <= 0:
            # A constant frame. Everything is "at the value", so mid-grey says
            # that honestly; scaling by a zero span would divide by zero and
            # scaling by an epsilon would turn rounding noise into structure.
            return np.full(values.shape, 0.5, dtype=np.float64)
        return np.clip((values - self.low) / span, 0.0, 1.0)

    def caption(self, unit: str = "") -> str:
        """``"0.41-6.24 m"``, for the panel label."""
        suffix = f" {unit}" if unit else ""
        return f"{self.low:.4g}-{self.high:.4g}{suffix}"


def display_range(target: torch.Tensor, valid: torch.Tensor | None = None) -> DisplayRange:
    """The range to draw ``target`` against, over its valid pixels only.

    ``valid`` is a ``(H, W)`` bool mask, or ``None`` when every pixel counts.
    Excluding the invalid ones is not cosmetic: depth's holes are stored as 0,
    so including them pins the low end at 0 for every frame and flattens the
    real range into the top of the ramp. ``NaN`` holes are worse — a percentile
    over them is ``NaN``, and the whole panel goes black.
    """
    values = target.detach().to(torch.float64).cpu().numpy().ravel()
    if valid is not None:
        values = values[valid.detach().cpu().numpy().ravel()]
    values = values[np.isfinite(values)]

    if values.size == 0:
        # Nothing to measure. The panel will be entirely invalid anyway, so any
        # range renders the same thing; a defined one keeps normalise() total.
        return DisplayRange(0.0, 1.0)

    low, high = np.percentile(values, _DISPLAY_PERCENTILES)
    return DisplayRange(float(low), float(high))


def voc_palette(count: int = 256) -> np.ndarray:
    """Pascal VOC's class colours as ``(count, 3)`` uint8.

    Generated by VOC's own bit-shuffle rather than hard-coded, so class 15 is
    ``(192, 128, 128)`` — the colour someone who has looked at VOC before will
    recognise as *person*. A palette invented here would be equally legible and
    would silently disagree with every VOC figure ever published, which is the
    kind of difference that costs an hour to notice.
    """
    palette = np.zeros((count, 3), dtype=np.uint8)
    for index in range(count):
        remaining, red, green, blue = index, 0, 0, 0
        for shift in range(8):
            red |= ((remaining >> 0) & 1) << (7 - shift)
            green |= ((remaining >> 1) & 1) << (7 - shift)
            blue |= ((remaining >> 2) & 1) << (7 - shift)
            remaining >>= 3
        palette[index] = (red, green, blue)
    return palette


def _greyscale(target: torch.Tensor, span: DisplayRange) -> np.ndarray:
    values = target.detach().to(torch.float64).cpu().numpy()
    # NaN survives normalise() as NaN and would cast to 0 silently. It is always
    # masked out by the caller for the one probe that produces it, but a target
    # with an unexpected NaN must not be drawn as black — nan_to_num puts it at
    # the top of the ramp, where it is at least visible.
    grey = np.nan_to_num(span.normalise(values), nan=1.0)
    scaled = np.round(grey * 255.0).astype(np.uint8)
    return np.repeat(scaled[..., None], 3, axis=-1)


def _normals(target: torch.Tensor) -> np.ndarray:
    """``(3, H, W)`` unit vectors as RGB, by the universal ``(n + 1) / 2``.

    Takes the first three channels only: ``SurfaceNormalTask`` emits a fourth
    when its uncertainty-aware loss is on, and that channel is a concentration
    parameter rather than a direction — folded into the colour it would tint
    the whole panel by how confident the head was.
    """
    directions = target.detach().to(torch.float64).cpu().numpy()[:3]
    rgb = np.clip((directions + 1.0) / 2.0, 0.0, 1.0)
    return np.round(np.moveaxis(rgb, 0, -1) * 255.0).astype(np.uint8)


def _binary(target: torch.Tensor) -> np.ndarray:
    """Non-zero is foreground, matching ``load_mask``'s own rule.

    Thresholded at 0.5 rather than at "non-zero" so a prediction — which
    arrives as a sigmoid probability, not a label — is drawn by the same rule
    ``binary_iou`` scores it by.
    """
    values = target.detach().to(torch.float64).cpu().numpy()
    mask = np.where(values > 0.5, 255, 0).astype(np.uint8)
    return np.repeat(mask[..., None], 3, axis=-1)


def _labels(target: torch.Tensor) -> np.ndarray:
    """Class indices through VOC's palette, with no intermediate conversion.

    The index is used as an index. That sounds too obvious to write down, and
    it is exactly what ``convert("L")`` broke when VOC's palette PNGs were first
    read: classes ``[0, 1, 15, 255]`` became ``[0, 38, 147, 220]``, which loads,
    trains and scores against labels that mean nothing.
    """
    indices = target.detach().cpu().numpy()
    palette = voc_palette()
    # Negative entries are the ignore label; they are overwritten with
    # INVALID_RGB by the caller, and are clipped here only so the lookup is in
    # range rather than wrapping round to a real class's colour.
    safe = np.clip(np.round(indices).astype(np.int64), 0, len(palette) - 1)
    return palette[safe]


def target_to_rgb(
    target: torch.Tensor,
    style: TargetStyle,
    span: DisplayRange | None = None,
) -> np.ndarray:
    """Draw ``target`` as an ``(H, W, 3)`` uint8 array, per ``style``.

    ``span`` is required for a scalar map and ignored otherwise. It is passed in
    rather than derived here so a prediction can be drawn against the *target's*
    range — deriving it per call is what makes a systematically scaled
    prediction look correct.

    Invalid pixels are painted :data:`INVALID_RGB` last, after the colouriser
    has run, so no colouriser needs to know the convention and none of them can
    disagree about it.
    """
    if style.kind in COMPOSITE_KINDS:
        drawn_by = {"boxes": "panels.draw_boxes", "matches": "matches.draw_matches"}
        raise ValueError(
            f"A {style.kind!r} target is drawn onto the frames it belongs to, not as "
            f"a panel of its own. Use visbench.viz.{drawn_by[style.kind]}."
        )

    if style.kind in ("magnitude", "depth"):
        if span is None:
            raise ValueError(
                f"A {style.kind} target needs a display range. Compute it once from "
                "the target with display_range() and pass the same one for the "
                "prediction, or a prediction at half the target's scale draws "
                "identically to a correct one."
            )
        rgb = _greyscale(target, span)
    elif style.kind == "normals":
        rgb = _normals(target)
    elif style.kind == "binary":
        rgb = _binary(target)
    elif style.kind == "labels":
        rgb = _labels(target)
    else:  # pragma: no cover - Kind is exhaustive above
        raise ValueError(f"No colouriser for kind {style.kind!r}")

    if style.invalid is not None:
        mask = style.invalid(target).detach().cpu().numpy()
        rgb = rgb.copy()
        rgb[mask] = INVALID_RGB
    return rgb
