#!/usr/bin/env python
"""Regenerate the documentation's measured tables from the record corpus.

Every measured table in this repository was hand-copied from a terminal until
this existed, and one of them had drifted by the time anyone noticed. The tables
are now delimited by HTML comments and rewritten from
``results/corpus/visbench.jsonl``, so the published numbers and the committed
records cannot disagree.

:data:`MARKED_FILES` lists the files scanned for markers — one per probe page
under ``docs/probes/``, since the reference was split from a single
``docs/tasks.md`` into a page each. A file with no markers is an **error**, not
a silently-skipped no-op, so moving a table without updating this list fails
loudly rather than leaving a board frozen at whatever it last said.

It is derived from :func:`visbench.list_probes` rather than typed out, so a new
probe cannot be added with a board that this script does not know to regenerate.
Three probes have no board on their own page and are listed as exceptions in
:data:`NO_PAGE_BOARD`: their numbers are in ``LEADERBOARD.md`` only.

    scripts/render_tables.py            # rewrite the marked files in place
    scripts/render_tables.py --check    # exit 1 if it would change anything

``--check`` is what ``tests/test_readme.py`` runs, so a stale table fails the
fast suite rather than shipping to PyPI, where a version number can never be
reused.

A marker looks like::

    <!-- visbench:board task=edge metrics=edge_correlation,mae,rmse -->
    ...generated...
    <!-- /visbench:board -->

`metrics` is optional and narrows the *rankable* columns for width. It cannot
drop a diagnostic or the ceiling of a metric it keeps — see
``render.render_board``, which enforces that rather than trusting the caller.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from visbench.results.leaderboard import group_comparable  # noqa: E402
from visbench.results.render import render_board, render_leaderboard  # noqa: E402
from visbench.results.writer import iter_records  # noqa: E402

CORPUS = REPO / "results" / "corpus" / "visbench.jsonl"
#: Every file holding ``visbench:board`` markers. Each must contain at least
#: one; see the module docstring.
#: Probes whose page links `LEADERBOARD.md` instead of carrying a generated
#: board. Not an oversight: `docs/tasks.md` never had a section for these three,
#: so splitting it could not produce one, and inventing a board here would mean
#: writing a marker whose table nobody had reviewed the surrounding prose for.
#: Delete a name from this set and add the marker to its page in one change.
NO_PAGE_BOARD = frozenset({"depth", "surface_normal", "generic_segmentation"})

#: Which level each probe's page lives under. Read from the task classes rather
#: than typed, so a probe that moves tier cannot leave a stale path here.
_LEVEL_DIRECTORY = {"high_level": "high-level", "mid_level": "mid-level", "low_level": "low-level"}


def _probe_pages() -> list[Path]:
    """Every probe page that should carry a board, from the registry.

    Derived rather than listed because a hand-written list is the failure this
    project has already shipped once: `slurm/corpus.sbatch` held twelve probes
    where `build_corpus.sh` held thirteen, and `corner` was unschedulable for a
    whole release because each file was self-consistent.
    """
    import visbench
    from visbench.registry import get_task_class

    pages = []
    for name in sorted(visbench.list_probes()):
        if name in NO_PAGE_BOARD:
            continue
        # The CLASS, never a constructed probe: `level` is a class attribute,
        # and `get_probe("detection")` raises because `num_classes` has no
        # default -- a wrong `num_classes` does not raise, so it is required on
        # purpose. Constructing sixteen probes to read one class attribute would
        # also load every task module's dependencies for nothing.
        level = _LEVEL_DIRECTORY[get_task_class(name).level]
        pages.append(REPO / "docs" / "probes" / level / f"{name}.md")
    return pages


MARKED_FILES = _probe_pages()
LEADERBOARD = REPO / "LEADERBOARD.md"

PREAMBLE = """<!-- Generated by scripts/render_tables.py. Do not edit by hand. -->

# VisBench leaderboard

Every board below is generated from
[`results/corpus/visbench.jsonl`][corpus], the committed record corpus. Nothing
here is typed in, so a number on this page and a number in a record cannot
disagree.

**A board is one comparability group**, not one task name. Two runs appear
together only when every choice that decides what their numbers *mean* agrees —
protocol, dataset fingerprint, pooling request, training budget, frozen-ness —
so the only remaining difference is the backbone. The digest under each table
identifies the group; see `visbench/results/leaderboard.py` for the rules.

**Read the ordering as one defensible ordering, not the ordering.** Several of
these tasks rank their backbones differently depending on which metric you ask,
and where that happens the board says so beneath it. Bolding is per column for
the same reason.

Every number is **frozen** — a linear probe on features from a backbone in
`eval()` with gradients off. Fine-tuned runs answer a different question and are
never pooled with these.

[corpus]: https://github.com/turhancan97/VisBench/blob/main/results/corpus/visbench.jsonl
"""

# The body is "anything that is not another marker", not a lazy `.*?`.
#
# A lazy match cannot express "stop at the first close marker" when the body may
# be *empty*: with `-->\n` consumed by the open group there is nothing left for
# `.*?\n` to match, so an empty pair fails and the match runs on to the next
# pair's close marker instead -- swallowing the open marker in between. Placing
# eight empty markers in the README and regenerating produced four boards and
# silently deleted four markers, which is how this is known rather than assumed.
MARKER = re.compile(
    r"(?P<open><!-- visbench:board (?P<attrs>[^>]*?) -->\n)"
    r"(?P<body>(?:(?!<!--\s*/?\s*visbench:board).)*)"
    r"(?P<close><!-- /visbench:board -->)",
    re.DOTALL,
)


def parse_attrs(text: str) -> dict[str, str]:
    return dict(pair.split("=", 1) for pair in text.split() if "=" in pair)


def board_for(task: str, metrics: list[str] | None, heading_level: int) -> str:
    """The one board for ``task``, refusing anything but exactly one group.

    A task with two comparability groups cannot be rendered into a single README
    table without choosing between them, and choosing silently is how a table
    starts describing a run nobody meant to publish. The corpus has held such a
    pair before: two `edge` groups differing only in ``target_scale``, scoring
    0.047 and 0.456.
    """
    records = [record for record in iter_records(CORPUS) if record.task == task]
    if not records:
        raise SystemExit(f"No records for task {task!r} in {CORPUS}")

    groups = group_comparable(records)
    if len(groups) != 1:
        described = "\n".join(f"  - {key.describe()}" for key in groups)
        raise SystemExit(
            f"{task!r} has {len(groups)} comparability groups, so there is no "
            f"single table to render:\n{described}\n"
            "Narrow the corpus or give the marker a group digest."
        )

    key, group = next(iter(groups.items()))
    return render_board(group, key=key, metrics=metrics, heading_level=heading_level)


def rewrite(text: str) -> str:
    def replace(match: re.Match[str]) -> str:
        attrs = parse_attrs(match.group("attrs"))
        task = attrs["task"]
        metrics = attrs["metrics"].split(",") if attrs.get("metrics") else None
        level = int(attrs.get("heading", 3))
        body = board_for(task, metrics, level)
        return f"{match.group('open')}{body}\n{match.group('close')}"

    updated = MARKER.sub(replace, text)

    # Every marker that went in must come back out. A regex that consumed one
    # would otherwise delete a table and report success -- see MARKER above.
    for marker in ("<!-- visbench:board", "<!-- /visbench:board -->"):
        if updated.count(marker) != text.count(marker):
            raise SystemExit(
                f"Marker count changed for {marker!r}: "
                f"{text.count(marker)} -> {updated.count(marker)}. "
                "Refusing to write a file that lost a board."
            )
    return updated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any generated table is out of date, without writing",
    )
    args = parser.parse_args()

    stale: list[str] = []
    rendered: dict[Path, str] = {}
    total = 0

    for path in MARKED_FILES:
        current = path.read_text()
        marker_count = len(MARKER.findall(current))
        if not marker_count:
            raise SystemExit(
                f"No visbench:board markers found in {path}. Either a table was "
                "moved without updating MARKED_FILES, or this file no longer "
                "belongs in it."
            )
        total += marker_count
        updated = rewrite(current)
        rendered[path] = updated
        if updated != current:
            stale.append(path.name)

    # The whole corpus, every group, nothing narrowed. The docs show the boards
    # their prose discusses; this is the one that shows what exists.
    board = PREAMBLE + "\n" + render_leaderboard(iter_records(CORPUS)) + "\n"
    if not (LEADERBOARD.exists() and LEADERBOARD.read_text() == board):
        stale.append(LEADERBOARD.name)

    if not stale:
        print(f"{total} boards across {len(MARKED_FILES)} file(s), LEADERBOARD.md current")
        return 0

    if args.check:
        print(
            f"{' and '.join(stale)} out of date against {CORPUS.name}.\n"
            "Run scripts/render_tables.py to regenerate.",
            file=sys.stderr,
        )
        return 1

    for path, text in rendered.items():
        path.write_text(text)
    LEADERBOARD.write_text(board)
    print(
        f"{total} boards -> {', '.join(p.name for p in MARKED_FILES)}, "
        f"full leaderboard -> {LEADERBOARD.name}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
